language: cpp
sudo: false
os:
- linux
- osx
compiler:
- gcc
- clang
addons:
  apt:
    packages:
    - qt5-default
install:
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew ls | grep -wq qt5 || brew install qt5;
  fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then export PATH=$PATH:/usr/local/opt/qt5/bin;
  fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then npm install -g appdmg;
  fi
env:
  global:
    secure: WaZq3f6KIAc0dnR4WOXYWDvUYiqlrzsZC/PQse47FnvC0oQC65J5w3kJOj/P26DgsUEqKQF3ukXogkM2mp5pS4+CMgivEmQmAbgQTtwcKpC5HPZxgI+8FgkCjcalJKWGWYoxlScNVNiKMs+89ApcSQE9kH9PZeUS9dukN2Php1U=
addons:
  coverity_scan:
    project:
      name: "IJHack/qtpass"
      description: "Build submitted via Travis CI"
    notification_email: brouwer@annejan.com
    build_command_prepend: "qmake; make clean"
    build_command:   "make"
    branch_pattern: coverity_scan
script:
- qmake -v
- qmake -Wall qtpass.pro
- make -j$(nproc)
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then macdeployqt QtPass.app;
  fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then appdmg appdmg.json qtpass-$(grep ^VERSION qtpass.pro | cut -d " " -f 6).dmg;
  fi
notifications:
  irc:
    channels:
    - chat.freenode.net#IJhack
    on_success: change
    on_failure: always
