language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

before_install:
  - QtMkspec=$CC
  - $CC --version

script:
  - cd qtpass
  - qmake -v
  - qmake -spec linux-$QtMkspec -Wall qtpass.pro
  - make -j$(nproc)

notifications:
  
  irc: 
    channels:
      - "chat.freenode.net#IJhack"
    on_success: change
    on_failure: always

matrix:
  allow_failures:
    - os: osx

